controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_link1
      - joint_link11
      - joint_link2
      - joint_link22
      - joint_link3
      - joint_link33
      - joint_link4
      - joint_link44
      - joint_link5
      - joint_link51
      - joint_link52
      - joint_link53
initial:  # Define initial robot poses per group
  - group: arm
    pose: base
  - group: hand
    pose: grip