arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  gains:
    joint1:
      p: 100
      d: 10
      i: 0.01
      i_clamp: 1
    joint2:
      p: 100
      d: 10
      i: 0.01
      i_clamp: 1
    joint3:
      p: 100
      d: 10
      i: 0.01
      i_clamp: 1
    joint4:
      p: 100
      d: 10
      i: 0.01
      i_clamp: 1
    joint5:
      p: 100
      d: 10
      i: 0.01
      i_clamp: 1
    joint6:
      p: 100
      d: 10
      i: 0.01
      i_clamp: 1
hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_link1
    - joint_link11
    - joint_link2
    - joint_link22
    - joint_link3
    - joint_link33
    - joint_link4
    - joint_link44
    - joint_link5
    - joint_link51
    - joint_link52
    - joint_link53
  gains:
    joint_link1:
      p: 100
      d: 10
      i: 0.01
      i_clamp: 1
    joint_link11:
      p: 100
      d: 10
      i: 0.01
      i_clamp: 1
    joint_link2:
      p: 100
      d: 10
      i: 0.01
      i_clamp: 1
    joint_link22:
      p: 100
      d: 10
      i: 0.01
      i_clamp: 1
    joint_link3:
      p: 100
      d: 10
      i: 0.01
      i_clamp: 1
    joint_link33:
      p: 100
      d: 10
      i: 0.01
      i_clamp: 1
    joint_link4:
      p: 100
      d: 10
      i: 0.01
      i_clamp: 1
    joint_link44:
      p: 100
      d: 10
      i: 0.01
      i_clamp: 1
    joint_link5:
      p: 100
      d: 10
      i: 0.01
      i_clamp: 1
    joint_link51:
      p: 100
      d: 10
      i: 0.01
      i_clamp: 1
    joint_link52:
      p: 100
      d: 10
      i: 0.01
      i_clamp: 1
    joint_link53:
      p: 100
      d: 10
      i: 0.01
      i_clamp: 1
